### PR TITLE
None

### PR DESCRIPTION
**Pull request by gitchomik**

### CODE REVIEW

**Comment by tonerdo** [comment]
@gitchomik what are your thoughts on being able to also disable history? Also, I notice your commit isn't connected to your Github username, are you fine with this?

**Comment by gitchomik** [comment]
@tsolarin: For me, It's not a problem, that commit isn't connected to my Github username. Disabling history could be next step (the elegant way should use early exit, but currently the dirty way is to set .MaxItem = 0).

**Comment by tonerdo** [comment]
What about `ReadLine.History.Disable()`? And then `ReadLine.History.Enabled` to get whether or not (`true`/`false`) history is enabled. I'd love to know your thoughts

/cc @gitchomik

**Comment by tonerdo** [comment]
@gitchomik please merge the latest change to master. I updated the test script and I want the CI to run on this PR using that. Thanks!!!

**Comment by tonerdo** [comment]
@gitchomik deliberate?

**Pull request closed without merging**
