### PR TITLE
Refactor Tests

### PR DESCRIPTION
**Pull request by rubberduck203**
I was having a bit of trouble following the tests at times.
This PR extracts a lot of the commonly duplicated code for creating `ConsoleKeyInfo` instances.
It also converts manual `for` loops into maps for readability.
I'm hoping this helps keep the tests maintainable into the future.

The new extension classes may or may not be useful in the main code base.
I didn't think about how they might be leveraged elsewhere yet.

### CODE REVIEW

**Review by Latency — APPROVED** [review]
Looks good to me!  Where did you come up with the const character values?

**Comment by rubberduck203** [comment]
At first I just set a breakpoint, but then I found this [ASCII control character table](http://jkorpela.fi/chars/c0.html) and the [UTF-8 codepoint table](https://en.wikipedia.org/wiki/UTF-8) for cross referencing.

**Comment by Latency** [comment]
@rubberduck203 reopen #43.  It is good!
Fix #39 by reverting the last 2 files in that PR or have Tony just cherry-pick the ClearLine() method into his.

**Review by tonerdo — APPROVED** [review]
Thanks for the clean up

**Pull request merged**
