### PR TITLE
Fix #30: Delete has not been implemented

### LINKED ISSUE #30: Delete does not work / has not been implemented
Delete inserts a character and corrupt prompt as opposed to removing the character after the cursor.

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by tonerdo** [comment]
Hi @IntelOrca thanks for the PR, sorry it took me this long to get to it. This change is welcome, please add this new key binding to the `Shortcut Guide` in the readme. Thanks!

**Comment by IntelOrca** [comment]
@tonerdo done

**Comment by tonerdo** [comment]
Awesome @IntelOrca I'd be merging this in later today. It'll be part of the next release I'm planning for the middle of this month. Thanks

**Comment by tonerdo** [comment]
Awesome @IntelOrca I'd be merging this in later today. It'll be part of the next release I'm planning for the middle of this month. Thanks for the contribution

**Pull request merged**
