### PR TITLE
History now has a global and per-call override.

### LINKED ISSUE #24: Add option to disable history
History should be able to be disabled on a global level:

`ReadLine.DisableHistory = true;`

And overridden on a call level:

`ReadLine.Read("", "", true);`
`ReadLine.Read("", "", false);`

### PR DESCRIPTION
**Pull request by psylenced**
History now has a global setting to enable or disable it.

Read() now has a parameter to enable or disable history on a per-call basis.

Fixes #24

### CODE REVIEW

**Comment by psylenced** [comment]
Please note - I do not current have vs2017 installed on my local machine so the above changes were made blind and need testing.

**Comment by psylenced** [comment]
@tsolarin did you get a chance to follow this up?

**Comment by tonerdo** [comment]
@chris-gh sorry for the delay. I'll take a look this weekend

**Comment by tonerdo** [comment]
@chris-gh I was thinking we could just keep the `DisableHistory` property and remove the override. I'm trying to not have too much arguments in the `ReadLine` method.

**Comment by tonerdo** [comment]
This is going into the next release. Thanks @psylenced

**Pull request merged**
