### PR TITLE
Add backwards AutoComplete

### PR DESCRIPTION
**Pull request by Guad**
Pressing Shift-Tab will traverse the autocomplete list in backward order, in case you missed it when mashing tab. I had to modify a couple of methods so it'd work, let me know if you'd prefer it another way.
Also, the `BuildKeyInput` method could be cleaner at detecting key modifiers, but I'll leave it at your discretion.
Feature requested by #6

### CODE REVIEW

**Review by tonerdo — APPROVED** [review]
This is good. Can you please add an entry for the `Shift+Tab` shortcut in the readme file

**Comment by tonerdo** [comment]
Thanks a lot @Guad, your contributions are greatly appreciated!!!

**Comment by tonerdo** [comment]
@Guad are you interested in becoming a collaborator?

**Comment by Guad** [comment]
Nah I'm good. I've discovered this project from the [c# digest newsletter](https://csharpdigest.net/) and wanted to lend a hand

**Comment by tonerdo** [comment]
ok @Guad your help is much appreciated!

**Pull request merged**
